const renderDefault = {
  root: {
    isRoot: true,
    translate: [0, 0, 0],
    rotate: [0, 0, 0],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    scale: [1, 1, 1],
    children: ['green'],
    color: [0, 1, 0, 1],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  green: {
    translate: [1, -1, 0],
    rotate: [0, 0, 0],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['blue'],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  blue: {
    translate: [0, 2, -1],
    rotate: [0, 0, 0],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: [],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
};
const crank = {
  info: {
    numCrank: 2,
    planeLen: 1,
    axisLen: 2,
    headLen: 0.5,
    rotSpeed: 1,
  },
  root: {
    isRoot: true,
    translate: [-1, -1, -1],
    rotate: [0, -1, 0],
    scale: [1, 1, 1],
    children: ['c0101'],
    color: [1, 0, 0, 1],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0101: {
    translate: [0, 0, -1],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['c0102'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0102: {
    translate: [0, -1, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['c0103'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0103: {
    translate: [0, 0, -0.5],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['c0104', 'c0106'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0104: {
    translate: [0, 0, -0.5],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['c0105'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0105: {
    translate: [0, 1, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['c0201'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0106: {
    translate: [0, 2, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['c0107'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0107: {
    translate: [0, 0.5, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0201: {
    translate: [0, 0, -1],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0.5, 0, 1],
    children: ['c0202'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0202: {
    translate: [0, 1, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0.5, 0, 1],
    children: ['c0203'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0203: {
    translate: [0, 0, -0.5],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0.5, 0, 1],
    children: ['c0204', 'c0206'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0204: {
    translate: [0, 0, -0.5],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0.5, 0, 1],
    children: ['c0205'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0205: {
    translate: [0, -1, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0.5, 0, 1],
    children: ['end'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0206: {
    translate: [0, 2, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0.5, 0, 1],
    children: ['c0207'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  c0207: {
    translate: [0, 0.5, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0.5, 0, 1],
    children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  end: {
    translate: [0, 0, -1],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0, 1, 1],
    children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
};

const person = {
  info: {
    numNode: 7 + 7 + 1,
    lenLegArm: 1,
    lenFrame: 0.5
  },
  root: {
    isRoot: true,
    translate: [0, 0, -2],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    children: ['ll01', 'rl01', 'upBody'],
    color: [1, 0, 0, 1],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  ll01: {
    translate: [-0.4, 0, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['ll02'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  ll02: {
    translate: [0, -1, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['ll03'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  ll03: {
    translate: [0, -1, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0, 1, 1],
    children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  rl01: {
    translate: [0.4, 0, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['rl02'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  rl02: {
    translate: [0, -1, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['rl03'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  rl03: {
    translate: [0, -1, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0, 1, 1],
    children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  upBody: {
    translate: [0, 1.5, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [1, 0, 0, 1],
    children: ['la01', 'ra01', 'head'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  la01: {
    translate: [-0.7, 0, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['la02'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  la02: {
    translate: [-0.1, -1, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['la03'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  la03: {
    translate: [0, -1, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0, 1, 1],
    children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  ra01: {
    translate: [0.7, 0, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['ra02'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  ra02: {
    translate: [0.1, -1, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 1, 0, 1],
    children: ['ra03'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  ra03: {
    translate: [0, -1, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0, 1, 1],
    children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
  head: {
    translate: [0, 0.7, 0],
    rotate: [0, 0, 0],
    scale: [1, 1, 1],
    color: [0, 0, 1, 1],
    children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
    shape: 'sphere',
  },
};

const hand = {
	info: {
	  numNode: 1+1+3+4*4,
    fingerName: ['th', 'if', 'mf', 'rf', 'pk'],
    fingerTog: {
      th: false,
      if: false,
      mf: false,
      rf: false,
      pk: false,
    },
    thInitRot: [0, 0, 0, 0.1, 0],
    fingerRot: {
      th: [0, 0, 1, 0.8],
      if: [0, 0.8, 1.2, 0.96],
      mf: [0, 0.9, 1.16, 0.94],
      rf: [0, 0.9, 1.2, 1],
      pk: [0, 0.88, 1.2, 1.2],
    },
	},
	root: {
	  isRoot: true,
	  translate: [0, 2, -3],
	  rotate: [0, 1.57, 0],
	  scale: [1, 1, 1],
	  color: [1, 0, 0, 1],
	  children: ['th01', 'if01', 'mf01', 'rf01', 'pk01'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	th01: {
	  translate: [0, -0.35, 0.45],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['th02'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	th02: {
	  translate: [0.35, -1, 0.5],
	  rotate: [-0.3, 1.27, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['th03'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	th03: {
	  translate: [0.03, -0.7, 0],
	  rotate: [0, 0, 0.1],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['th04'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	th04: {
	  translate: [0.01, -0.45, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	if01: {
	  translate: [-0.65, -2, 0.44],
	  rotate: [-0.16, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['if02'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	if02: {
	  translate: [0.17, -0.63, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['if03'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	if03: {
	  translate: [0.25, -0.48, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['if04'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	if04: {
	  translate: [0.3, -0.37, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	mf01: {
	  translate: [-0.7, -2.05, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['mf02'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	mf02: {
	  translate: [0.09, -0.75, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['mf03'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	mf03: {
	  translate: [0.26, -0.57, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['mf04'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	mf04: {
	  translate: [0.37, -0.44, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	rf01: {
	  translate: [-0.55, -1.93, -0.4],
	  rotate: [0.15, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['rf02'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	rf02: {
	  translate: [0.07, -0.63, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['rf03'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	rf03: {
	  translate: [0.23, -0.5, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['rf04'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	rf04: {
	  translate: [0.3, -0.38, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	pk01: {
	  translate: [-0.33, -1.74, -0.8],
	  rotate: [0.4, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['pk02'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	pk02: {
	  translate: [0.03, -0.5, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['pk03'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	pk03: {
	  translate: [0.2, -0.39, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: ['pk04'],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
	pk04: {
	  translate: [0.23, -0.34, 0],
	  rotate: [0, 0, 0],
	  scale: [1, 1, 1],
	  color: [0, 1, 0, 1],
	  children: [],
    rotateSpd: [0, 0, 0],
    rotateNode: [0, 0, 0],
    rotateNodeSpd: [0, 0, 0],
    calcedCoord: [0, 0],
		shape: 'sphere',
	},
};

var renderObjMapper = {
  crank: {
    data: crank,
    renderBefore: (data, dt) => {
      data.root.rotate[2] -= data.info.rotSpeed * dt;

      let planeTheta = -data.root.rotate[2];
      let headTheta = Math.asin(data.info.planeLen * Math.sin(planeTheta) / data.info.axisLen);
      let axisTheta = planeTheta - headTheta;

      data.c0103.rotate[2] = axisTheta;
      data.c0104.rotate[2] = -axisTheta;
      data.c0106.rotate[2] = headTheta;

      planeTheta = -data.root.rotate[2];
      headTheta = Math.asin(data.info.planeLen * Math.sin(planeTheta) / data.info.axisLen);
      axisTheta = planeTheta + headTheta;

      data.c0203.rotate[2] = axisTheta;
      data.c0204.rotate[2] = -axisTheta;
      data.c0206.rotate[2] = -headTheta;
    },
  },
  person: {
    data: person,
    renderBefore: (data, dt) => {
    },
  },
  hand: {
    data: hand,
    renderBefore: (data, dt) => {
      for (let i = 0; i < 5; i++) {
        const type = data.info.fingerName[i];
        for (let j = 1; j < 4; j++) {
          if (type === 'th') {
            if (j === 1)
              continue;
            if (!data.info.fingerTog.th) {
              if (data[`th0${j}`].rotate[2] > data.info.thInitRot[j]) {
                data[`th0${j}`].rotate[2] -= 0.02;
              }
            } else {
              if (data[`th0${j}`].rotate[2] < data.info.fingerRot.th[j]) {
                data[`th0${j}`].rotate[2] += 0.02;
              }
            }
          } else {
            if (!data.info.fingerTog[`${type}`]) {
              if (data[`${type}0${j}`].rotate[2] > 0) {
                data[`${type}0${j}`].rotate[2] -= 0.02;
              }
            } else {
              if (data[`${type}0${j}`].rotate[2] < data.info.fingerRot[`${type}`][j]) {
                data[`${type}0${j}`].rotate[2] += 0.02;
              }
            }
          }
        }
      }
    },
  },
  default: {
    data: renderDefault,
    renderBefore: (data, dt) => {
    },
  },
};
